### PR TITLE
Fix #70: 'Microsoft.VisualStudio.ExtensionManager.GalleryOnlineExtension' not found

### LINKED ISSUE #70: Error when trying to Export extensions in vs 2022 preview
**Describe the bug**
When I try to Export or Import extensions in Visual Studio Community 2022 (64-bit) - Preview, Version 17.6.0 Preview 2.0 , Extension Manager 2022 Version: 1.1.82, then I get this error message:
"
Extension Manager 2022
Could not load type
'Microsoft.VisualStudio.ExtensionManager.GalleryOnlineExtensio n' from assembly 'Microsoft.VisualStudio.ExtensionEngine,
Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
"

**To Reproduce**
1. Open VS 2022 Preview  Version 17.6.0 Preview 2.0
2. Select Extensions --> Import and Export Extensions --> Export Extensions or Import Extensions
3. Error message pops up.

**Expected behavior**
Get window where to select extensions to export/import

**Screenshots**
image

--
Eigil

### PR DESCRIPTION
**Pull request by loop8ack**
I've described in https://github.com/madskristensen/ExtensionPackTools/issues/70#issuecomment-1546908590 what i've done

### CODE REVIEW

**Comment by loop8ack** [comment]
The second commit addresses #73

**Comment by madskristensen** [comment]
Thank you!!

**Comment by loop8ack** [comment]
#71 is a duplicate of #70, this should also be closed.

And are you still actively developing this project?

If not, would it be ok if I took it over?
I have a few ideas for features and how I would build the project, but they would go far beyond a pull request.

**Comment by madskristensen** [comment]
@loop8ack I'm no longer actively developing this project. You are welcome to take over. Do you wish to fork and get write permissions to this repo?

**Comment by loop8ack** [comment]
@madskristensen 
I think it would be easiest for me if you transfer the repository to me.
Your name as the original author will of course remain in the ReadMe.

I have found this:
https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

If you want to keep the repository in your own account, write permissions are fine of course.

**Comment by loop8ack** [comment]
@madskristensen Do you have an answer to this?

**Comment by madskristensen** [comment]
You need to delete your repo `loop8ack/ExtensionPackTools` before I can transfer this to you

**Comment by loop8ack** [comment]
@madskristensen The repository is deleted

**Comment by madskristensen** [comment]
Transfer in progress...

**Comment by loop8ack** [comment]
@madskristensen Thank you :)

**Comment by loop8ack** [comment]
@madskristensen One more question: can you export me your AppVeyor configuration? There is an "Export YAML" function there

**Comment by madskristensen** [comment]
@loop8ack it's all in the appveyor.yml file in the root of this repo

**Comment by loop8ack** [comment]
@madskristensen 
Great, AppVeyor is up and running.

One (hopefully) final point:
I need to update the extension in the Marketplace.
I think it would be best if you mark the version under your name as deprecated. Then I will publish the new version under my publisher account.

**Comment by madskristensen** [comment]
Let me know when you published your version, then I'll take mine down

**Comment by loop8ack** [comment]
@madskristensen I'm online and ready to go :)

**Comment by madskristensen** [comment]
I've removed my extension from the marketplace

**Comment by loop8ack** [comment]
The versions for 2017 and 2019 are still online

**Comment by madskristensen** [comment]
Are you not just releasing a version for 2022? Why would I remove the older one if people want to use them?

**Comment by loop8ack** [comment]
I wanted to ensure support for both 2017 and 2019 versions, so for future updates.

However, I have concerns about the process, as I will have to publish the extension under a different ID since yours is still in use, presumably because the Marketplace retains it for compatibility reasons? Do you have any insights or suggestions regarding this?

Ideally, I would like users to be able to install updates without any disruption, but I guess that achieving a seamless transition may be challenging.

**Comment by madskristensen** [comment]
You must change the `ProductID` and VS will not be able to update from my extension version to yours. It would be a huge security issue if that was possible, so this is by design.

**Comment by loop8ack** [comment]
Ok, then it's only possible with a different product ID. I have already changed them.

But we can also leave 2017 and 2019 online, but then I will need your help again later when I have a relevant update.

Do you know what the procedure would be if you leave your versions online but mark them as obsolete and write an info about it? Is that possible? That way, users would be able to be informed about the project takeover.

PS:
Ok, I just realised that's not possible.

**Comment by madskristensen** [comment]
That is unfortunately not possible today

**Pull request merged**
