### PR TITLE
Fixed #42

### LINKED ISSUE #42: WindowStyle.None error dialog on Export Extensions... action.  (v0.6.72)
Hello,

I've just updated the extension to the latest version  (v0.6.72) through Visual Studio Extension Manager. 
It was working without a problem before, but now when I use the following menu option
Extensions > Import and Export Extensions > Export Extensions...
I get and error window with the following content :

Microsoft Visual Studio
Extension Manager 2019

WindowStyle.None is the only valid value for WindowStyle when AllowsTransparency is true.

image

Could this be related to the latest commit : #41 ?

Thanks.

My environment is as follows :
Microsoft Windows 10 Enterprise Version	10.0.18363 Build 18363
Microsoft Visual Studio Professional 2019 Version 16.8.3
VisualStudio.16.Release/16.8.3+30804.86
Microsoft .NET Framework Version 4.8.03752

### PR DESCRIPTION
**Pull request by astrohart**
* Removed `WindowStyle.None` from `ImportWindow` XAML
* Set `AllowsTransparency` to `False` in the `ImportWindow` XAML
* Move call to `InitializeWindowChrome` to `OnSourceInitialized` override in Code-Behind (fixing the chrome and making the window be like a dialog box)
* Widened the `ImportWindow` to improve usage of screen real estate.
* Removed the `Style` resources and set the properties for `FontFamily`, `FontWeight`, and `FontSize` directly on the top two `Label`s directly, in order to then make them respond to theming
* Fixed the access key mnemonics on the `OK` button to say `"_Import"`, `"_Install"`, and `"_Export"` instead of `"&Import`" etc.

### CODE REVIEW

**Comment by astrohart** [comment]
@madskristensen 

In my tests, the theming works:

image

The figure above shows the **Export Extensions** dialog box responding to the Dark Theme in VS 2019 Community, with the top two labels clearly visible, per Issue #42 

image

The above shows the same dialog when the `Light` or `Blue` themes are applied.

**Comment by astrohart** [comment]
Please btw -- for now -- disregard my `astrohart:astrohart` branch.  That's a branch on which much more extensive changes (in order to improve code smell) are stashed.  I am not wanting to pull-request or merge those yet, @madskristensen because I need your okay first.

**Comment by astrohart** [comment]
@madskristensen I've just done an end to end test and the extension passes. I think it's okay to merge and release.

**Comment by madskristensen** [comment]
Thanks!!!

**Pull request merged**
