### PR TITLE
Fixed #31

### LINKED ISSUE #31: Import and Export dialog boxes really need a "Select All/Deselect All" check box.
Hi,

I have a very numerous amount of extensions to import/export, and it's tiring simply clicking all the check boxes in the list, one at a time.

It would be nice to have a single check box at the top of the list, called **Select/deselect all** and then clicking it to place a check mark in it makes all the check boxes in the list get checked, and clicking it again to clear its check mark clears the check marks from all items in the list.  I'll fork this repo and then I will submit a Pull request, in order to address this issue.

In order to avoid code collisions, I'll submit my pull request to a `astrohart` branch.

### PR DESCRIPTION
**Pull request by astrohart**
Added a **Select/deselect all** check box to the Import/Export dialog box.  When the `IsChecked` property of this box is toggled, all the check boxes in the list are toggled to match.

### CODE REVIEW

**Review by astrohart — COMMENTED** [review]
Just to let you know, I had ReSharper installed and it wanted to do a Code Cleanup according to my own style rules, so ignore variables where `var` is used instead of the type name etc.  The real lines to focus on are lines 91-97 of `src/ExtensionManager.Shared/Importer/ImportWindow.xaml.cs` and lines 13 and 25-27 of `src/ExtensionManager.Shared/Importer/ImportWindow.xaml`.

**Comment by madskristensen** [comment]
Thanks for the PR. There seem to be merge conflicts. Can you do a rebase?

**Comment by astrohart** [comment]
I’m sorry, but I am a git newbie. I don’t know how to do a re-base and I’m afraid of breaking you something if I try random commands.

Please kindly send the Git Bash commands I should run.

Brian

**Comment by astrohart** [comment]
Hi Mads-
  
  
   
  
  
   Brian Hart again.
  
  
   
  
  
   To what commit do you wish me to rebase?
   
   
  
  
   I am concerned that if I execute the wrong git commands, I'll accidentally destroy/overwrite your work or the work of others.
  
  
   
  
  
   Please advise how you suggest I'd proceed.
  
  
   
  
  
   -Brian Hart
  
  
   
    On 01/03/2021 10:47 AM Mads Kristensen <notifications@github.com> wrote:
   
   
    
   
   
    
   
   
   Thanks for the PR. There seem to be merge conflicts. Can you do a rebase?

**Comment by astrohart** [comment]
Hi Mads-

What I am proposing to do is:

1. Delete/retract this specific PR
2 Then, do a 'pull' and then a 'push' to my local (forked) repo
3. Create new Pull Request

That should, I think, do the trick.

-Brian

**Pull request closed without merging**
