### PR TITLE
fix save / open file dialog mismatch

### LINKED ISSUE #14: Import extensions shows save instead of open dialog
The TryGetFilePath helper method called from ImportCommand shows the save dialog - it does not check for an existing file and gives an overwrite prompt if you do select one.
The import command then works as expected with the file (if it exists).
I think this either needs 2 methods, or a flag to say Open or Save?

### PR DESCRIPTION
**Pull request by Thieum**
Fixes error introduced in previous PR that merged duplicated code, that was not so much duplicated.
fixes #14

### CODE REVIEW

**Comment by Thieum** [comment]
fixes #13 as well.

**Comment by Thieum** [comment]
fixes #16 too

**Comment by madskristensen** [comment]
Thank you for the PR!!! Unfortunately, I made these changes myself recently and didn't notice your PR in time

**Comment by Thieum** [comment]
sounds good, sorry for the inconvenience :(

**Comment by madskristensen** [comment]
@Thieum, it's me that sorry for not checking to see your PR in time. Still much appreciated. Thank you

**Pull request closed without merging**
